# Generated by Django 3.2.7 on 2021-09-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('run_coach', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=16)),
                ('contrato', models.FloatField()),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coachee',
            fields=[
                ('run_coachee', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('apellido_m', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=16)),
                ('contrato', models.FloatField()),
            ],
            options={
                'db_table': 'coachee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cantro', models.DateField()),
                ('clausula', models.TextField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_empresa', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('contrato', models.FloatField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=20)),
                ('nota', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_incador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor_meta', models.FloatField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'objetivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'plan_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReunionAvance',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'reunion_avance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReunionIni',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('antecedente_coachee', models.TextField()),
                ('objetivo_proceso', models.TextField()),
                ('indicador_exito', models.TextField()),
                ('participante', models.TextField()),
            ],
            options={
                'db_table': 'reunion_ini',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_acordada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('estado', models.FloatField()),
                ('asignacion_acuerdos', models.TextField()),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('archivo', models.TextField()),
                ('fecha_subida', models.DateField()),
                ('run_coach', models.OneToOneField(db_column='run_coach', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.coach')),
                ('fecha_vista', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentacion',
                'managed': False,
            },
        ),
    ]
