# Generated by Django 3.2.7 on 2021-10-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('run_coach', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=200)),
                ('contrato', models.FloatField()),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coachee',
            fields=[
                ('run_coachee', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('apellido_m', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=200)),
                ('contrato', models.FloatField()),
            ],
            options={
                'db_table': 'coachee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id_doc', models.FloatField(primary_key=True, serialize=False)),
                ('archivo', models.TextField()),
                ('fecha_subida', models.DateField()),
                ('fecha_vista', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_empresa', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('contrato', models.FloatField()),
                ('nombre_jefe', models.CharField(max_length=50)),
                ('correo_jefe', models.CharField(max_length=60)),
                ('telefono_jefe', models.IntegerField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_pregunta', models.FloatField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=20)),
                ('nota', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_encuesta', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_incador', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor_meta', models.FloatField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'objetivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id_plan', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'plan_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('fecha_contrato', models.DateField()),
                ('clausula', models.TextField()),
            ],
            options={
                'db_table': 'proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('participante', models.TextField()),
                ('tipo_reunion', models.CharField(max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('antecedente_coachee', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reunion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_acordada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.FloatField()),
                ('asignacion_acuerdos', models.TextField()),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
    ]
