# Generated by Django 3.2.9 on 2021-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivosC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
    ]
