# Generated by Django 3.2.8 on 2021-11-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='AUTH_USER',
        ),
    ]
